Iris 분류 - 결정 트리(Decision Tree)

1. 데이터 전처리, 탐색

In [2]:
from sklearn.datasets import load_iris
iris=load_iris()

In [3]:
iris.keys() #Iris 데이터 엑세스하는 방법. 속성들의 키를 반환

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
# data - X (sl, sw, pl, pw)
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [5]:
iris.feature_names #X값의 이름 (꽃받침의 너비/길이, 꽃잎의 너비/길이)

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
iris.target[:5] #target=y

array([0, 0, 0, 0, 0])

In [7]:
iris.target_names #y값의 이름

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [8]:
import pandas as pd
df=pd.DataFrame(iris.data, columns=iris.feature_names)
df['species']=iris.target #df에'species' 열 추가 -> iris.target 값 할당
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [9]:
iris.data.shape, iris.target.shape #X, y의 shape

((150, 4), (150,))

In [10]:
df.species.value_counts() #species열에 있는 고유한 값들의 빈도를 계산

species
0    50
1    50
2    50
Name: count, dtype: int64

In [12]:
print(iris.DESCR) #설명(description)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [13]:
df.describe() #기초 통계자료

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)     species  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

2. 학습과 테스트 데이터로 분리

In [14]:
from sklearn.model_selection import train_test_split #데이터셋을 훈련 세트와 테스트 세트로 무작위로 나누는데 사용
import numpy as np

In [15]:
# X는 2차원이라서 대문자로, y는 1차원이라 소문자로 표기
# train : test = 3 : 1 (test_size=0.25가 디폴트)

X_train, X_test, y_train, y_test=train_test_split(
    iris.data, iris.target, random_state=2023
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [16]:
np.unique(y_train, return_counts=True) #y_train 값의 분포

#return_counts=True: 빈도를 함께 반환하도록 지정하는 매개변수

(array([0, 1, 2]), array([34, 37, 41], dtype=int64))

In [17]:
#y값의 분포를 균일하게 => stratify 매개변수 활용. 목표값을 기준으로 층화추출(stratified sampling) 수행
X_train,X_test, y_train, y_test=train_test_split(
    iris.data, iris.target, random_state=2023
)
np.unique(y_train, return_counts=True)

(array([0, 1, 2]), array([34, 37, 41], dtype=int64))

In [18]:
#학습 데이터와 테스트 데이터의 비율(test_size)
X_train, X_test, y_train,y_test=train_test_split(
    iris.data, iris.target, random_state=2023
)
np.unique(y_train, return_counts=True)

#0에 해당하는 라벨 34번, 1에 해당하는 라벨 37번, 2에 해당하는 라벨 41번 => 불균형

(array([0, 1, 2]), array([34, 37, 41], dtype=int64))

In [19]:
X_train,X_test,y_train,y_test=train_test_split(
    iris.data, iris.target, random_state=2023,
    stratify=iris.target, test_size=0.2
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [20]:
np.unique(y_train, return_counts=True) #클래스의 분포가 균일하게 유지되었음을 확인

(array([0, 1, 2]), array([40, 40, 40], dtype=int64))

3. 학습 (훈련, train)

In [21]:
from sklearn.tree import DecisionTreeClassifier
#분할하면서 예/아니오 질문을 통해 학습하는 모델. 각 분할 지점에서 최적의 결정을 내리는 방식으로 동작

In [22]:
dtc=DecisionTreeClassifier()

In [23]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [25]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

4. 예측 (Prediction)

In [27]:
rf=pd.DataFrame({'y 실제값':y_test, 'y 예측값': pred})
rf.head()

y 실제값  y 예측값
0      2      2
1      0      0
2      1      1
3      1      1
4      0      0

In [28]:
X_test[:5]

array([[6.3, 3.3, 6. , 2.5],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 2.5, 3. , 1.1],
       [5.9, 3. , 4.2, 1.5],
       [4.6, 3.6, 1. , 0.2]])

5. 평가 (Evaluation)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

#모델의 예측 결과와 실제 라벨 간의 정확도를 계산. 0~1 사이의 실수 반환(1에 가까울수록 모델의 성능이 좋음)
#y_test: 모델의 예측을 평가하기 위한 테스트 데이터셋에 대한 실제 라벨
#pred: 모델이 예측한 라벨

In [30]:
dtc.score(X_test, y_test)

0.9666666666666667